[build]
builder = "nixpacks"
buildCommand = "npm run build"

[deploy]
startCommand = "npm run db:migrate && npm run db:seed-municipalities && npm run start"
healthcheckPath = "/api/auth/status"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[service]
internalPort = 3000
